name: null

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - gym-atari=0.17
  - jupyterlab=2.0
  - matplotlib=3.2
  - pip=20.0
  - pip:
    - -r file:requirements.txt
  - pandas=1.0
  - pytorch=1.5
  - python=3.7
  - pyvirtualdisplay=0.2
  - torchvision=0.6