name: null

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - gym-box2d=0.17
  - jupyterlab=2.1
  - matplotlib=3.2
  - nodejs=13
  - pandas=1.0
  - pip=20.0
  - pip:
    - -r file:requirements.txt
  - python=3.7
  - pytorch=1.4
  - pyvirtualdisplay=0.2

